### PR TITLE
Add i18n system

### PR DESCRIPTION
**Pull request by Toinane**
Hey! Thank you for your great work 😄 
I had some difficult with all english name for maps and items. So I adding a simple i18n system and my native language (french).

I not have translated gears for the moment as I don't want to take time to translate all if this work will not be useful 👍 But I can add it after if wanted!

### CODE REVIEW

**Comment by misenhower** [comment]
Hey @Toinane, first of all, thank you for your effort with this!

>I not have translated gears for the moment as I don't want to take time to translate all if this work will not be useful

Eventually, all map/gear name translations will be loaded automatically from SplatNet, so there's no need to do this manually. That's the next thing I plan on working on.

I need a little time to review this (and to check whether `vue-i18n` will handle all the internationalization needs of the site) but I really appreciate your help! I'll let you know if there are any issues 😄

**Comment by Toinane** [comment]
thank you for your response! 😃 let me know if I need to change something!

**Comment by misenhower** [comment]
Hey @Toinane, I just made a few tweaks to this and deployed it to production. You did a great job with this PR, and it really helped make things easier for me 😄

Thank you again for all your effort!

**Comment by Toinane** [comment]
Hey @misenhower happy that help you :D Thank you too for the great job it's really useful!

**Pull request merged**
