### PR TITLE
Remove Twitter from Frontend

### PR DESCRIPTION
**Pull request by catgirlinspace**
This removes Twitter references from the frontend, except for AboutView. The Twitter updater remains. The AboutView will require localization changes and should be updated to instead reference @splatoon3ink@splatoon3.ink.

https://twitter.com/Splatoon3ink/status/1675226978440593408?s=20
image
Screenshot for people rate-limited from accessing Twitter

### CODE REVIEW

**Comment by FieryFlames** [comment]
I don't really see a point in this? Twitter is going downhill but they're not dead yet and as far as I know the splatoon3.ink Twitter account is still posting

**Comment by catgirlinspace** [comment]
The most recent automated tweet was 22 hours ago. https://twitter.com/Splatoon3ink/status/1675202726307958785

**Comment by misenhower** [comment]
Hey thanks for the PR! I ended up just adding a new socials page here instead: https://splatoon3.ink/socials

Thank you!

**Comment by catgirlinspace** [comment]
whatever

**Pull request closed without merging**
